// src/components/page/footer.jsx
import PropTypes from "prop-types";
import React from "react";
import styled from "styled-components";
import { lightSeparator, strongTextColor, textColor } from "../color";
import Container from "../container";
import { devices } from "../helpers";

const Footer = styled.footer`
  border-top: 1px solid ${lightSeparator};
  color: ${textColor};
  font-size: 14px;
  padding: 24px 0;
  text-align: center;

  @media ${devices.tablet} {
    text-align: right;
  }
`;

const Link = styled.a`
  color: ${strongTextColor};
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
`;

function PageFooter({ licenseName, licenseUrl, repositoryUrl }) {
  return (
    <Footer>
      <Container>
        <p>
          O conteúdo desse blog está sob a licença{" "}
          <Link href={licenseUrl}>{licenseName}</Link>.
        </p>
        <p>
          <Link href={repositoryUrl}>Fork me on Github</Link>.
        </p>
      </Container>
    </Footer>
  );
}

PageFooter.propTypes = {
  licenseName: PropTypes.string.isRequired,
  licenseUrl: PropTypes.string.isRequired,
  repositoryUrl: PropTypes.string.isRequired,
};

export default PageFooter;

// blog/src/lib/components/Footer.svelte
<script>
	import Container from './Container.svelte';
</script>

<Container>
	<div>
		<p>
			O conteúdo desse site está sob a licença <a
				href="http://creativecommons.org/licenses/by/3.0/deed.pt_BR">Creative Commons Attribution</a
			>.
		</p>
		<p><a href="https://github.com/kplaube/blog">Fork me no Github</a>.</p>
	</div>
</Container>

<style>
	div {
		color: var(--secondary-color);
		border-top: 1px solid #f4f4f4;
		font-size: 0.8rem;
		margin: 4rem 0;
		padding-top: 2rem;
		text-align: right;
	}

	a {
		color: var(--primary-color);
	}
	a:hover {
		text-decoration: none;
	}
</style>
