// blog/src/lib/components/Header.svelte
<script lang="ts">
	export let avatar: string;
	export let description: string;
	export let title: string;
	export let url: string;
</script>

<header>
	<div class="inside-container">
		<a href={url}>
			<img src={avatar} alt="Avatar" />

			<div>
				<h1>{title}</h1>

				<span>{description}</span>
			</div>
		</a>
	</div>
</header>

<style>
	.inside-container {
		margin: 0 auto;
		max-width: 492px;
	}

	a {
		align-items: center;
		display: flex;
		text-decoration: none;
	}
	a:hover h1 {
		color: var(--primary-color);
	}
	a:hover img {
		filter: grayscale(60%);
	}

	header {
		padding: 3.5rem 0;
	}

	h1 {
		color: var(--brand-color);
		font-size: 1rem;
		font-weight: 300;
		letter-spacing: -0.96px;
		margin: 0 0 0.25rem;
		text-transform: uppercase;
	}

	img {
		background-color: var(--secondary-color);
		border-radius: 50%;
		height: 64px;
		margin-right: 16px;
		width: 64px;
	}

	span {
		color: var(--secondary-color);
		font-size: 1rem;
		font-weight: 300;
	}
</style>

// src/components/page/header.jsx
import { Mail } from "@styled-icons/feather/Mail";
import { Link } from "gatsby";
import PropTypes from "prop-types";
import React from "react";
import styled, { css } from "styled-components";
import { secondaryColor, textColor } from "../color";
import Container from "../container";
import { devices } from "../helpers";
import Brand from "./header-brand";

const BaseIconStyles = css`
  color: ${secondaryColor};
  width: 22px;
`;

const GreyMail = styled(Mail)`
  ${BaseIconStyles};
`;

const StyledHeader = styled.div`
  box-shadow: 0 -8px 16px 0 ${textColor};
  font-size: 1.1rem;
  margin-bottom: 24px;

  @media ${devices.tablet} {
    margin-bottom: 64px;
  }
`;

const HeaderContainer = styled(Container)`
  align-items: center;
  display: flex;
  height: 56px;
  justify-content: space-between;
  max-width: 974px;
`;

const StyledLink = styled(Link)`
  text-decoration: none;
`;

const StyledA = styled.a`
  text-decoration: none;
`;

function Header({ contact, siteTitle }) {
  return (
    <StyledHeader>
      <HeaderContainer>
        <StyledLink to="/">
          <Brand siteTitle={siteTitle} />
        </StyledLink>
        <div>
          <StyledA href={contact} title="Contato">
            <GreyMail />
          </StyledA>
        </div>
      </HeaderContainer>
    </StyledHeader>
  );
}

Header.propTypes = {
  contact: PropTypes.string.isRequired,
  siteTitle: PropTypes.string.isRequired,
};

export default Header;
